version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cv-frontend
      - cv-generator
      - cv-auth-backend
      - cv-file-validate
      - cv-hh-service

  cv-frontend:
    build:
      context: ./cv-frontend
    ports:
      - "5173:5173"
    depends_on:
      - cv-generator
      - cv-file-validate
      - cv-auth-backend
      - cv-hh-service
    
  cv-generator:
    build:
      context: ./cv-generator
    ports:
      - "3000:3000"
    
  cv-file-validate:
    build:
      context: ./cv-file-validate
    ports:
      - "8081:8081"

  cv-hh-service:
    build:
      context: ./cv-hh-service
    ports:
      - "8082:8082"
    
  cv-auth-backend:
    build:
      context: ./cv-auth-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: cv_auth_backend
      POSTGRES_PASSWORD: pass-cv1234
    ports:
      - "5432:5432"
    volumes:
      - ./cv-auth-backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: